resolver: lts-12.3

packages:
- .

extra-deps: 
  - alsa-mixer-0.2.0.3

flags: {}

extra-package-dbs: []

nix:
  enable: true
  packages: 
    - zlib
    - haskellPackages.alsa-core
    - haskellPackages.alsa
